name: GitHub Actions Demo
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Cypress run
      uses: cypress-io/github-action@v4
    with:
        test: npm run cy:run
    name: commit and push results
    uses: EndBug/add-and-commit@v9